name: "Clasp Deploy"
description: "Custom action to deploy using clasp"
inputs:
  ACCESS_TOKEN:
    description: "Access Token"
    required: true
  ID_TOKEN:
    description: "ID Token"
    required: true
  REFRESH_TOKEN:
    description: "Refresh Token"
    required: true
  CLIENTID:
    description: "Client ID"
    required: true
  CLIENTSECRET:
    description: "Client Secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: pre processing
      run: |
        yarn install --frozen-lockfile
      shell: bash
    - name: set environment variables
      run: |
        echo "ACCESS_TOKEN=${{ inputs.ACCESS_TOKEN }}" >> $GITHUB_ENV
        echo "ID_TOKEN=${{ inputs.ID_TOKEN }}" >> $GITHUB_ENV
        echo "REFRESH_TOKEN=${{ inputs.REFRESH_TOKEN }}" >> $GITHUB_ENV
        echo "CLIENTID=${{ inputs.CLIENTID }}" >> $GITHUB_ENV
        echo "CLIENTSECRET=${{ inputs.CLIENTSECRET }}" >> $GITHUB_ENV
      shell: bash
    - name: create clasprc.json
      run: npx ts-node ${{ github.action_path }}/index.ts
      shell: bash
    - name: deploy
      run: echo "y" | yes | head -n 1 | npx clasp push
      shell: bash
